### ISSUE TITLE
Dataflow Testing Roadmap

### ISSUE THREAD

**Issue by zoready** [readysettech/readyset#431]
# Dataflow Testing

We plan to further expand the testing of our core caching engine (dataflow), with the end goal of getting ReadySet production ready. 

### Memory Pressure Testing

If we try to allocate too much memory, the OS will OOMkill us and restart the ReadySet process. This should never happen; these tests will help us gain further confidence that this is indeed the case. If there are difficult to avoid situations where we do OOM, we should document them extensively.

- [X] Audit Subsystems for things that may grow unbounded in memory
- [X] Add visibility into which components are using memory in the system
- [X] Fix documentation for `--memory`
- [ ] https://github.com/readysettech/readyset/issues/241

### Eviction Testing

When the readyset process reaches the `READYSET_MEMORY_LIMIT` threshold in heap allocation, we begin evicting from the cache. While we already have tests that exercise this functionality, we should further expand on them since this is steady state behavior in production contexts. 

- [X] Add eviction operator to vertical DDL tests
- [X] Run fuzz test suite with evictions enabled
- [X] Add more queries to dataflow vertical proptests
- [ ] https://github.com/readysettech/readyset/issues/242

### Adapter Edge Case Testing

We want to ensure that the ReadySet adapter behaves correctly in the face of edge-case user behavior--like restarts, disconnects, and intertwining readyset-custom commands (`CREATE CACHE`, `SHOW READYSET STATUS`, etc.)

- [X] Ensure we are not using ReadySet when we should be proxying
- [X] Ensure we can do multiple add + drop query cycles and end up with correct results
- [X] Ensure we can restart and start caching as soon as we get the information from the views poll task

#### Add Generative Expressions in Postgres "Oracle" tests (Property-based tests that use postgres as the source of truth)

We have identified a couple of areas that we can expand our already extensive property-based tests: more testing of the write path, and generating arbitrary SQL expressions.

- [X] Implement Arbitrary for `DfType`
- [X] Generate `DfValues` based on a given `DfType`
- [X] Implement a `Strategy` to generate an arbitrary `Expr`
- [X] Generate `Expr` based on a given `DfType`
- [ ] https://github.com/readysettech/readyset/issues/243

#### Add more testing to the write path
- [X] Optimize Postgres `types` tests to speed up testing and cover more values
- [X] Inserting arrays of enums can fail in Postgres after altering the enum type
- [X] Inserting enum values can fail in Postgres after altering the enum type
