### ISSUE TITLE
High Availability (V1) Roadmap

### ISSUE THREAD

**Issue by zoready** [readysettech/readyset#433]
# High Availability (V1)

To achieve an initial form of high availability (dubbed as warm read HA), a ReadySet deployment should be able to: 

* Accept connections at all times
* Handle queries at all times, even if they need to be proxied to the primary database
* Serve warm reads from caches as often as possible
* Replicate writes from the primary database as often as possible

In addition to these availability requirements, the following should hold true:

* Proxied query queries should have a minimal overhead as compared to connecting directly to the primary db (ideally on par with pgbouncer, which introduces 10%-20% overhead).
* Warm read performance should remain competitive (ideally in the sub-millisecond range) 

## Background

Noria originally, and ReadySet subsequently, were designed to support this kind of highly available deployment. In Noria, domains could be scheduled onto multiple workers in a clustered deployment, and communicate with each other overTCP channels. Noria primarily used this to scale up throughput, but since then we've added preliminary support for replicating domains (intended for use with domains containing reader nodes) and running those replicas embedded within distinct adapter nodes.

Getting this functinality ready for prime time requires a little bit of extra work. We want to make sure that if instances die and restart, the cluster continues to be healthy, and continues to meet all of the above goals.

## Guarantees
A cluster with a single server and N adapters with embedded readers stays healthy in the presence of failures. If any single adapter is down, the other adapters should serve reads from the cache, receive replicated writes, handle connections, and proxy queries. If the server is down, the adapters should remain healthy and proxy everything. 

As long as at least one adapter is available, writes should always succeed, and reads should either serve cached or be proxied. Queries served from the cache may return stale data until the server becomes available again. 

### Milestone 1: Fix known bugs

- [ ] https://github.com/readysettech/readyset/issues/312
- [ ] https://github.com/readysettech/readyset/issues/313
- [ ] https://github.com/readysettech/readyset/issues/314
- [ ] https://github.com/readysettech/readyset/issues/311
- [ ] https://github.com/readysettech/readyset/issues/315
- [ ] https://github.com/readysettech/readyset/issues/316
- [ ] https://github.com/readysettech/readyset/issues/288
- [ ] https://github.com/readysettech/readyset/issues/298
- [ ] https://github.com/readysettech/readyset/issues/317
- [ ] https://github.com/readysettech/readyset/issues/318
- [ ] https://github.com/readysettech/readyset/issues/300

### Milestone 2: Additional testing & bug fixes
- [ ] https://github.com/readysettech/readyset/issues/246
- [ ] https://github.com/readysettech/readyset/issues/320
- [ ] https://github.com/readysettech/readyset/issues/352
